name: Github Actions Demo

on:
  push:
    branches: main
    paths-ignore: .github
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      enviroment: 
        description: 'Target'
        type: enviroment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name}}"
          echo "Branch: ${{ github.ref}}"
          

      - uses: actions/checkout@v4.1.0

      - name: List Files
        run: |
          echo "Repository:"
          tree
      
      
          
        
  
    
